model_name: efficientnet-b1-unet
encoder: efficientnet-b1
weights: imagenet
decoder: unet
lr: 8.317637711026709e-05
seed: 42
patience: 5
num_workers: 2
batch_size: 8
image_size: 512
epochs: 31
classes: 2
loss: CE
optimizer: Adam
scheduler: cosine
gpu: True
fast_dev_run: 0
all_data: 1
ds_path: 'data'
selected_folds: 4
bands: ['B02','B03','B04','B08']